/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <string.h>
#include "stm32f401xx_spi_driver.h"
#include "stm32f401xx_gpio_driver.h"


/*
 * SPI2 PIN CONFIGURATION
 * =====================
 * PB15 --> SPI2_MOSI (Master Output Slave Input) - Data sent from master
 * PB14 --> SPI2_MISO (Master Input Slave Output) - Data received from slave
 * PB13 --> SPI2_SCK  (Serial Clock) - Clock signal generated by master
 * PB12 --> SPI2_NSS  (Chip Select) - Slave selection signal
 * 
 * Alternate Function Mode: 5
 * (This tells the GPIO pins to use their alternate SPI functionality)
 */

void SPI2_GPIOInit(void)
{
	// Create a GPIO handle structure for SPI pins
	GPIO_Handle_t SPIPins;
	
	// Select GPIOB port
	SPIPins.pGPIOx = GPIOB;
	
	// Configure common settings for all SPI pins
	SPIPins.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;        // Use alternate function mode
	SPIPins.GPIO_PinConfig.GPIO_PinAltFunMode = 5;               // Select AF5 (SPI2 function)
	SPIPins.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;     // Push-pull output type
	SPIPins.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;      // Fast speed for SPI clock

	// Configure SCLK (Serial Clock) on PB13
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GPIO_Init(&SPIPins);

	// Configure MOSI (Master Output Slave Input) on PB15
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
	GPIO_Init(&SPIPins);

	// MISO (Master Input Slave Output) - Currently disabled
	// Uncomment below if slave response is needed
//	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
//	GPIO_Init(&SPIPins);

	// NSS (Chip Select) - Currently disabled
	// Using software slave management (SSM) instead of hardware NSS
//	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
//	GPIO_Init(&SPIPins);
}

void SPI2_Init(void)
{
	// Create an SPI handle structure
	SPI_Handle_t SPI2handle;

	// Point to SPI2 peripheral base address
	SPI2handle.pSPIx = SPI2;
	
	// Configure SPI2 parameters
	SPI2handle.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FD;       // Full-duplex: simultaneous TX and RX
	SPI2handle.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER; // This device is the master (generates clock)
	SPI2handle.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV2;     // Clock speed = PCLK / 2 (fastest)
	SPI2handle.SPIConfig.SPI_DFF = SPI_DFF_8BITS;                // Data frame format: 8-bit transfers
	SPI2handle.SPIConfig.SPI_CPOL = SPI_CPOL_HIGH;               // Clock polarity: idle high
	SPI2handle.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;                // Clock phase: data captured on rising edge
	SPI2handle.SPIConfig.SPI_SSM = SPI_SSM_EN;                   // Software slave management: NSS pin controlled by software

	// Initialize the SPI peripheral with the configured settings
	SPI_Init(&SPI2handle);
}

int main(void)
{
	// Test data to transmit via SPI
	char user_data[] = "Hello world!";

	// Step 1: Initialize GPIO pins for SPI2 (SCLK and MOSI)
	SPI2_GPIOInit();

	// Step 2: Initialize SPI2 peripheral with master mode configuration
	SPI2_Init();

	// Step 3: Enable Internal Slave Select (SSI)
	// This prevents MODF error (Mode Fault) when SSM is enabled
	// In software mode, this bit controls the NSS signal internally
	SPI_SSIConfig(SPI2, ENABLE);

	// Step 4: Enable the SPI peripheral to start operation
	SPI_PeripheralCtrl(SPI2, ENABLE);

	// Step 5: Send data via SPI2
	// Transmits the string "Hello world!" to the slave device
	// Data is sent as individual bytes (strlen = 12 bytes)
	SPI_SendData(SPI2, (uint8_t*)user_data, strlen(user_data));

	// Keep the program running indefinitely
	// In a real application, you might check transfer status or perform other tasks here
	while(1);

	return 0;
}


